### ISSUE TITLE
Awesome work - Thanks for uploading

### ISSUE THREAD

**Issue by LiamC12345** [chudonghao/FastNoisePreviewAppQt#1]

**Comment by chudonghao** [comment]
Sorry, I just saw it now. Is your problem solved?

**Comment by chudonghao** [comment]
> _No description provided._

Sorry, I just saw it now. Is your problem solved?

**Comment by chudonghao** [comment]
Sorry, I just saw it now. Is your problem solved?

**Comment by LiamC12345** [comment]
Yeah all good I got in touch with Auburn (Fast Noise 2 guy)
Thanks for getting back to me though :)
